// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('starter', ['ionic', 'starter.controllers', 'ionic.utils', 'starter.services']).run(function($ionicPlatform) {
    $ionicPlatform.ready(function() {
      if (window.cordova && window.cordova.plugins.Keyboard) {
        cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
        cordova.plugins.Keyboard.disableScroll(true);
      }
      if (window.StatusBar) {
        StatusBar.styleDefault();
      }
    });
  }).config(function($stateProvider, $urlRouterProvider) {
    $stateProvider.state('app', {
      url: '/app',
      abstract: true,
      templateUrl: 'templates/menu.html'
    }).state('app.partners', {
      url: '/partners',
      views: {
        'menuContent': {
          templateUrl: 'templates/partners.html',
          controller: 'CalcCtrl'
        }
      }
    }).state('app.about', {
      url: '/about',
      views: {
        'menuContent': {
          templateUrl: 'templates/about.html'
        }
      }
    });
    $urlRouterProvider.otherwise('/app/partners');
  });

}).call(this);
