// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('ionic.utils', []).factory('$localstorage', [
    '$window', function($window) {
      return {
        set: function(key, value) {
          return $window.localStorage[key] = value;
        },
        get: function(key, defaultValue) {
          return $window.localStorage[key] || defaultValue;
        },
        setObject: function(key, value) {
          return $window.localStorage[key] = JSON.stringify(value);
        },
        getObject: function(key) {
          return JSON.parse($window.localStorage[key] || '[]');
        }
      };
    }
  ]);

}).call(this);
