// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('starter.services', []).factory('Partners', [
    '$localstorage', function($localstorage) {
      var partners, partnersNumber;
      partners = $localstorage.getObject('partners');
      partnersNumber = $localstorage.get('partnersNumber', 0);
      return {
        all: function() {
          return partners;
        },
        remove: function(chat) {
          return partners.splice(partners.indexOf(chat), 1);
        },
        get: function(chatId) {
          var i, len, partner;
          for (i = 0, len = partners.length; i < len; i++) {
            partner = partners[i];
            if (partner.id === parseInt(chatId)) {
              return partner;
            }
          }
          return null;
        },
        getPartnersNumber: function() {
          return +partnersNumber;
        },
        saveAll: function(partners, partnersNumber) {
          console.log(partnersNumber);
          $localstorage.setObject('partners', partners);
          return $localstorage.set('partnersNumber', partnersNumber);
        }
      };
    }
  ]);

}).call(this);
